# Update this to match your needs.
accounts:
  - c4vr2.wam
  - stuckatsixpm
  - sixpm
  - tag 
contract: eosio.token:transfer
date-range:
  start: "2021-06-30T14:00:00"
  end: "2021-08-31T13:59:59"
currency: AUD
export-folder: transaction_csvs
endpoints:
  - https://api-wax.eosauthority.com/v2/history/get_actions
  - https://waxapi.ledgerwise.io/v2/history/get_actions