# Update this file to match your needs.
mode: fast # fast/robust: fast uses a single endpoint to return data quickly. Robust aggregates data from 3 nodes if possible.
max-retries: 3 # how many times to retry before aborting
accounts:
  # - c4vr2.wam
  - stuckatsixpm
  # - sixpm
  # - tag 
contract: eosio.token:transfer
date-range:
  # start: "2021-06-30T14:00:00"
  # end: "2021-08-31T13:59:59"
  start: "2022-01-30T14:00:00"
  end: "2022-02-09T13:59:59"
currency: AUD
export-folder: transaction_csvs
endpoints:
  - https://api-wax.eosauthority.com/v2/history/get_actions
  - https://waxapi.ledgerwise.io/v2/history/get_actions