# Update this file to match your needs.
# fast/full: 
#   "fast" mode uses a single endpoint to return data quickly.
#   "full" mode aggregates data from 3 nodes if possible.

mode: full
max-retries: 3 # how many times to retry before aborting
accounts:
  - c4vr2.wam
  - stuckatsixpm
  - sixpm
  - tag 
contract: eosio.token:transfer
date-range:
  # start: "2021-06-30T14:00:00"
  # end: "2021-08-31T13:59:59"
  start: "2022-01-30T14:00:00"
  end: "2022-02-09T13:59:59"
currency: AUD
export-folder: transaction_csvs
exclude-endpoints:
  - 3dkrenderwax
  - bp.wecan
